SELECT TOP (1000) [full_name]
      ,[dob]
      ,[contact_number]
      ,[email]
      ,[state]
      ,[selectcity]
      ,[pincode]
      ,[full_address]
      ,[create_user_id]
      ,[password]
      ,[confpassword]
  FROM [formDB].[dbo].[master_master_tbl]
