SELECT TOP (1000) [full_name]
      ,[dob]
      ,[contac_number]
      ,[email]
      ,[state]
      ,[city]
      ,[pincode]
      ,[full_address]
      ,[create_user_id]
      ,[password]
      ,[conf_password]
  FROM [formDB].[dbo].[master_master_tbl]
